name: 💡 Feature/Idea
description: Have a new idea/feature? Please suggest!
title: "[FEATURE] <description>"
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the enhancement you propose (also include what you tried and what worked)
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this idea?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our Discord community [here](http://discord.eddiehub.org)
        Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)
